global using FraudSys.Domain.LimiteCliente.Repository;
global using FraudSys.Domain.LimiteCliente.Validator;
global using FraudSys.Domain.LimiteCliente;
global using FraudSys.Domain.Transacao;
global using FraudSys.Domain.Transacao.Enum;
global using FraudSys.Domain.Transacao.Repository;
global using FraudSys.Domain.Transacao.Validator;
global using FraudSys.Application.Repository;
global using FraudSys.Application.SeedWork;